// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailAdapter is an autogenerated mock type for the EmailAdapter type
type EmailAdapter struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: address, content
func (_m *EmailAdapter) SendEmail(address string, content string) error {
	ret := _m.Called(address, content)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(address, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailAdapter creates a new instance of EmailAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailAdapter {
	mock := &EmailAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
