// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "github.com/arturspolizel/payments/model"
	mock "github.com/stretchr/testify/mock"
)

// MerchantController is an autogenerated mock type for the MerchantController type
type MerchantController struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MerchantController) Create(_a0 model.Merchant) (uint, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Merchant) (uint, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(model.Merchant) uint); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(model.Merchant) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *MerchantController) Get(_a0 uint) (model.Merchant, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (model.Merchant, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) model.Merchant); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.Merchant)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMerchantController creates a new instance of MerchantController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantController {
	mock := &MerchantController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
