// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "github.com/arturspolizel/payments/model"
	mock "github.com/stretchr/testify/mock"
)

// MerchantRepository is an autogenerated mock type for the MerchantRepository type
type MerchantRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MerchantRepository) Create(_a0 model.Merchant) (uint, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Merchant) (uint, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(model.Merchant) uint); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(model.Merchant) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *MerchantRepository) Get(_a0 uint) (model.Merchant, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (model.Merchant, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) model.Merchant); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.Merchant)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: startId, pageSize
func (_m *MerchantRepository) List(startId uint, pageSize uint) ([]model.Merchant, error) {
	ret := _m.Called(startId, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) ([]model.Merchant, error)); ok {
		return rf(startId, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) []model.Merchant); ok {
		r0 = rf(startId, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(startId, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMerchantRepository creates a new instance of MerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantRepository {
	mock := &MerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
