// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "github.com/arturspolizel/payments/model"
	mock "github.com/stretchr/testify/mock"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: payment
func (_m *PaymentRepository) Create(payment model.Payment) uint {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uint
	if rf, ok := ret.Get(0).(func(model.Payment) uint); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *PaymentRepository) Get(id uint) model.Payment {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Payment
	if rf, ok := ret.Get(0).(func(uint) model.Payment); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Payment)
	}

	return r0
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
